apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30080   # optional: 30000-32767 range mein specify kar sakte ho
  type: NodePort
